/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ForbiddenRouteImport } from './routes/forbidden'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as StyleguideRouteImport } from './routes/styleguide'
import { Route as AuthenticatedAppRouteRouteImport } from './routes/_authenticated/_app/route'
import { Route as AuthenticatedChangePasswordRouteImport } from './routes/_authenticated/change-password'
import { Route as TvDoctorIdRouteImport } from './routes/tv.$doctorId'
import { Route as AuthenticatedAppAppointmentsRouteImport } from './routes/_authenticated/_app/appointments'
import { Route as AuthenticatedAppApprovalsRouteImport } from './routes/_authenticated/_app/approvals'
import { Route as AuthenticatedAppAuditLogsRouteImport } from './routes/_authenticated/_app/audit-logs'
import { Route as AuthenticatedAppBillingRouteImport } from './routes/_authenticated/_app/billing'
import { Route as AuthenticatedAppCashRegisterRouteImport } from './routes/_authenticated/_app/cash-register'
import { Route as AuthenticatedAppCompanySettingsRouteImport } from './routes/_authenticated/_app/company-settings'
import { Route as AuthenticatedAppConsultationsRouteImport } from './routes/_authenticated/_app/consultations'
import { Route as AuthenticatedAppDashboardRouteImport } from './routes/_authenticated/_app/dashboard'
import { Route as AuthenticatedAppDepartmentsRouteImport } from './routes/_authenticated/_app/departments'
import { Route as AuthenticatedAppDoctorsRouteImport } from './routes/_authenticated/_app/doctors'
import { Route as AuthenticatedAppDoctorsNowRouteImport } from './routes/_authenticated/_app/doctors-now'
import { Route as AuthenticatedAppEmergencyRouteImport } from './routes/_authenticated/_app/emergency'
import { Route as AuthenticatedAppFormularyRouteImport } from './routes/_authenticated/_app/formulary'
import { Route as AuthenticatedAppHandoverRouteImport } from './routes/_authenticated/_app/handover'
import { Route as AuthenticatedAppHelpRouteImport } from './routes/_authenticated/_app/help'
import { Route as AuthenticatedAppInventoryRouteImport } from './routes/_authenticated/_app/inventory'
import { Route as AuthenticatedAppLabRouteImport } from './routes/_authenticated/_app/lab'
import { Route as AuthenticatedAppLabTestsRouteImport } from './routes/_authenticated/_app/lab-tests'
import { Route as AuthenticatedAppLeaveApprovalsRouteImport } from './routes/_authenticated/_app/leave-approvals'
import { Route as AuthenticatedAppMyAppointmentsRouteImport } from './routes/_authenticated/_app/my-appointments'
import { Route as AuthenticatedAppMyBillsRouteImport } from './routes/_authenticated/_app/my-bills'
import { Route as AuthenticatedAppMyDayRouteImport } from './routes/_authenticated/_app/my-day'
import { Route as AuthenticatedAppMyLeaveRouteImport } from './routes/_authenticated/_app/my-leave'
import { Route as AuthenticatedAppMyRecordsRouteImport } from './routes/_authenticated/_app/my-records'
import { Route as AuthenticatedAppMyScheduleRouteImport } from './routes/_authenticated/_app/my-schedule'
import { Route as AuthenticatedAppNursingRouteImport } from './routes/_authenticated/_app/nursing'
import { Route as AuthenticatedAppOpdQueueRouteImport } from './routes/_authenticated/_app/opd-queue'
import { Route as AuthenticatedAppOtRouteImport } from './routes/_authenticated/_app/ot'
import { Route as AuthenticatedAppPackagesRouteImport } from './routes/_authenticated/_app/packages'
import { Route as AuthenticatedAppPatientsRouteImport } from './routes/_authenticated/_app/patients'
import { Route as AuthenticatedAppPharmacyRouteImport } from './routes/_authenticated/_app/pharmacy'
import { Route as AuthenticatedAppReportsRouteImport } from './routes/_authenticated/_app/reports'
import { Route as AuthenticatedAppSettingsRouteImport } from './routes/_authenticated/_app/settings'
import { Route as AuthenticatedAppStaffRouteImport } from './routes/_authenticated/_app/staff'
import { Route as AuthenticatedAppSupportTicketsRouteImport } from './routes/_authenticated/_app/support-tickets'
import { Route as AuthenticatedAppSystemIssuesRouteImport } from './routes/_authenticated/_app/system-issues'
import { Route as AuthenticatedAppTariffsRouteImport } from './routes/_authenticated/_app/tariffs'
import { Route as AuthenticatedAppUnpaidRouteImport } from './routes/_authenticated/_app/unpaid'
import { Route as AuthenticatedAppUsersRouteImport } from './routes/_authenticated/_app/users'
import { Route as AuthenticatedAppWardSetupRouteImport } from './routes/_authenticated/_app/ward-setup'
import { Route as AuthenticatedAppWardsRouteImport } from './routes/_authenticated/_app/wards'
import { Route as TvDepartmentDepartmentIdRouteImport } from './routes/tv.department.$departmentId'
import { Route as AuthenticatedAppAdmissionsNewRouteImport } from './routes/_authenticated/_app/admissions_.new'
import { Route as AuthenticatedAppConsultationsVisitIdRouteImport } from './routes/_authenticated/_app/consultations_.$visitId'
import { Route as AuthenticatedAppDoctorsDoctorIdRouteImport } from './routes/_authenticated/_app/doctors_.$doctorId'
import { Route as AuthenticatedAppOtBookingIdRouteImport } from './routes/_authenticated/_app/ot_.$bookingId'
import { Route as AuthenticatedAppPatientsPatientIdRouteImport } from './routes/_authenticated/_app/patients_.$patientId'
import { Route as AuthenticatedAppPatientsNewRouteImport } from './routes/_authenticated/_app/patients_.new'
import { Route as AuthenticatedAppPharmacyPrescriptionIdRouteImport } from './routes/_authenticated/_app/pharmacy_.$prescriptionId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ForbiddenRoute = ForbiddenRouteImport.update({
  id: '/forbidden',
  path: '/forbidden',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const StyleguideRoute = StyleguideRouteImport.update({
  id: '/styleguide',
  path: '/styleguide',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppRouteRoute = AuthenticatedAppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedChangePasswordRoute =
  AuthenticatedChangePasswordRouteImport.update({
    id: '/change-password',
    path: '/change-password',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const TvDoctorIdRoute = TvDoctorIdRouteImport.update({
  id: '/tv/$doctorId',
  path: '/tv/$doctorId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppAppointmentsRoute =
  AuthenticatedAppAppointmentsRouteImport.update({
    id: '/appointments',
    path: '/appointments',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppApprovalsRoute =
  AuthenticatedAppApprovalsRouteImport.update({
    id: '/approvals',
    path: '/approvals',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppAuditLogsRoute =
  AuthenticatedAppAuditLogsRouteImport.update({
    id: '/audit-logs',
    path: '/audit-logs',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppBillingRoute = AuthenticatedAppBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AuthenticatedAppRouteRoute,
} as any)
const AuthenticatedAppCashRegisterRoute =
  AuthenticatedAppCashRegisterRouteImport.update({
    id: '/cash-register',
    path: '/cash-register',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppCompanySettingsRoute =
  AuthenticatedAppCompanySettingsRouteImport.update({
    id: '/company-settings',
    path: '/company-settings',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppConsultationsRoute =
  AuthenticatedAppConsultationsRouteImport.update({
    id: '/consultations',
    path: '/consultations',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppDashboardRoute =
  AuthenticatedAppDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppDepartmentsRoute =
  AuthenticatedAppDepartmentsRouteImport.update({
    id: '/departments',
    path: '/departments',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppDoctorsRoute = AuthenticatedAppDoctorsRouteImport.update({
  id: '/doctors',
  path: '/doctors',
  getParentRoute: () => AuthenticatedAppRouteRoute,
} as any)
const AuthenticatedAppDoctorsNowRoute =
  AuthenticatedAppDoctorsNowRouteImport.update({
    id: '/doctors-now',
    path: '/doctors-now',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppEmergencyRoute =
  AuthenticatedAppEmergencyRouteImport.update({
    id: '/emergency',
    path: '/emergency',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppFormularyRoute =
  AuthenticatedAppFormularyRouteImport.update({
    id: '/formulary',
    path: '/formulary',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppHandoverRoute =
  AuthenticatedAppHandoverRouteImport.update({
    id: '/handover',
    path: '/handover',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppHelpRoute = AuthenticatedAppHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => AuthenticatedAppRouteRoute,
} as any)
const AuthenticatedAppInventoryRoute =
  AuthenticatedAppInventoryRouteImport.update({
    id: '/inventory',
    path: '/inventory',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppLabRoute = AuthenticatedAppLabRouteImport.update({
  id: '/lab',
  path: '/lab',
  getParentRoute: () => AuthenticatedAppRouteRoute,
} as any)
const AuthenticatedAppLabTestsRoute =
  AuthenticatedAppLabTestsRouteImport.update({
    id: '/lab-tests',
    path: '/lab-tests',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppLeaveApprovalsRoute =
  AuthenticatedAppLeaveApprovalsRouteImport.update({
    id: '/leave-approvals',
    path: '/leave-approvals',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppMyAppointmentsRoute =
  AuthenticatedAppMyAppointmentsRouteImport.update({
    id: '/my-appointments',
    path: '/my-appointments',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppMyBillsRoute = AuthenticatedAppMyBillsRouteImport.update({
  id: '/my-bills',
  path: '/my-bills',
  getParentRoute: () => AuthenticatedAppRouteRoute,
} as any)
const AuthenticatedAppMyDayRoute = AuthenticatedAppMyDayRouteImport.update({
  id: '/my-day',
  path: '/my-day',
  getParentRoute: () => AuthenticatedAppRouteRoute,
} as any)
const AuthenticatedAppMyLeaveRoute = AuthenticatedAppMyLeaveRouteImport.update({
  id: '/my-leave',
  path: '/my-leave',
  getParentRoute: () => AuthenticatedAppRouteRoute,
} as any)
const AuthenticatedAppMyRecordsRoute =
  AuthenticatedAppMyRecordsRouteImport.update({
    id: '/my-records',
    path: '/my-records',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppMyScheduleRoute =
  AuthenticatedAppMyScheduleRouteImport.update({
    id: '/my-schedule',
    path: '/my-schedule',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppNursingRoute = AuthenticatedAppNursingRouteImport.update({
  id: '/nursing',
  path: '/nursing',
  getParentRoute: () => AuthenticatedAppRouteRoute,
} as any)
const AuthenticatedAppOpdQueueRoute =
  AuthenticatedAppOpdQueueRouteImport.update({
    id: '/opd-queue',
    path: '/opd-queue',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppOtRoute = AuthenticatedAppOtRouteImport.update({
  id: '/ot',
  path: '/ot',
  getParentRoute: () => AuthenticatedAppRouteRoute,
} as any)
const AuthenticatedAppPackagesRoute =
  AuthenticatedAppPackagesRouteImport.update({
    id: '/packages',
    path: '/packages',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppPatientsRoute =
  AuthenticatedAppPatientsRouteImport.update({
    id: '/patients',
    path: '/patients',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppPharmacyRoute =
  AuthenticatedAppPharmacyRouteImport.update({
    id: '/pharmacy',
    path: '/pharmacy',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppReportsRoute = AuthenticatedAppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedAppRouteRoute,
} as any)
const AuthenticatedAppSettingsRoute =
  AuthenticatedAppSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppStaffRoute = AuthenticatedAppStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => AuthenticatedAppRouteRoute,
} as any)
const AuthenticatedAppSupportTicketsRoute =
  AuthenticatedAppSupportTicketsRouteImport.update({
    id: '/support-tickets',
    path: '/support-tickets',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppSystemIssuesRoute =
  AuthenticatedAppSystemIssuesRouteImport.update({
    id: '/system-issues',
    path: '/system-issues',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppTariffsRoute = AuthenticatedAppTariffsRouteImport.update({
  id: '/tariffs',
  path: '/tariffs',
  getParentRoute: () => AuthenticatedAppRouteRoute,
} as any)
const AuthenticatedAppUnpaidRoute = AuthenticatedAppUnpaidRouteImport.update({
  id: '/unpaid',
  path: '/unpaid',
  getParentRoute: () => AuthenticatedAppRouteRoute,
} as any)
const AuthenticatedAppUsersRoute = AuthenticatedAppUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedAppRouteRoute,
} as any)
const AuthenticatedAppWardSetupRoute =
  AuthenticatedAppWardSetupRouteImport.update({
    id: '/ward-setup',
    path: '/ward-setup',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppWardsRoute = AuthenticatedAppWardsRouteImport.update({
  id: '/wards',
  path: '/wards',
  getParentRoute: () => AuthenticatedAppRouteRoute,
} as any)
const TvDepartmentDepartmentIdRoute =
  TvDepartmentDepartmentIdRouteImport.update({
    id: '/tv/department/$departmentId',
    path: '/tv/department/$departmentId',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAppAdmissionsNewRoute =
  AuthenticatedAppAdmissionsNewRouteImport.update({
    id: '/admissions_/new',
    path: '/admissions/new',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppConsultationsVisitIdRoute =
  AuthenticatedAppConsultationsVisitIdRouteImport.update({
    id: '/consultations_/$visitId',
    path: '/consultations/$visitId',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppDoctorsDoctorIdRoute =
  AuthenticatedAppDoctorsDoctorIdRouteImport.update({
    id: '/doctors_/$doctorId',
    path: '/doctors/$doctorId',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppOtBookingIdRoute =
  AuthenticatedAppOtBookingIdRouteImport.update({
    id: '/ot_/$bookingId',
    path: '/ot/$bookingId',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppPatientsPatientIdRoute =
  AuthenticatedAppPatientsPatientIdRouteImport.update({
    id: '/patients_/$patientId',
    path: '/patients/$patientId',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppPatientsNewRoute =
  AuthenticatedAppPatientsNewRouteImport.update({
    id: '/patients_/new',
    path: '/patients/new',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppPharmacyPrescriptionIdRoute =
  AuthenticatedAppPharmacyPrescriptionIdRouteImport.update({
    id: '/pharmacy_/$prescriptionId',
    path: '/pharmacy/$prescriptionId',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/forbidden': typeof ForbiddenRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/styleguide': typeof StyleguideRoute
  '/change-password': typeof AuthenticatedChangePasswordRoute
  '/tv/$doctorId': typeof TvDoctorIdRoute
  '/appointments': typeof AuthenticatedAppAppointmentsRoute
  '/approvals': typeof AuthenticatedAppApprovalsRoute
  '/audit-logs': typeof AuthenticatedAppAuditLogsRoute
  '/billing': typeof AuthenticatedAppBillingRoute
  '/cash-register': typeof AuthenticatedAppCashRegisterRoute
  '/company-settings': typeof AuthenticatedAppCompanySettingsRoute
  '/consultations': typeof AuthenticatedAppConsultationsRoute
  '/dashboard': typeof AuthenticatedAppDashboardRoute
  '/departments': typeof AuthenticatedAppDepartmentsRoute
  '/doctors': typeof AuthenticatedAppDoctorsRoute
  '/doctors-now': typeof AuthenticatedAppDoctorsNowRoute
  '/emergency': typeof AuthenticatedAppEmergencyRoute
  '/formulary': typeof AuthenticatedAppFormularyRoute
  '/handover': typeof AuthenticatedAppHandoverRoute
  '/help': typeof AuthenticatedAppHelpRoute
  '/inventory': typeof AuthenticatedAppInventoryRoute
  '/lab': typeof AuthenticatedAppLabRoute
  '/lab-tests': typeof AuthenticatedAppLabTestsRoute
  '/leave-approvals': typeof AuthenticatedAppLeaveApprovalsRoute
  '/my-appointments': typeof AuthenticatedAppMyAppointmentsRoute
  '/my-bills': typeof AuthenticatedAppMyBillsRoute
  '/my-day': typeof AuthenticatedAppMyDayRoute
  '/my-leave': typeof AuthenticatedAppMyLeaveRoute
  '/my-records': typeof AuthenticatedAppMyRecordsRoute
  '/my-schedule': typeof AuthenticatedAppMyScheduleRoute
  '/nursing': typeof AuthenticatedAppNursingRoute
  '/opd-queue': typeof AuthenticatedAppOpdQueueRoute
  '/ot': typeof AuthenticatedAppOtRoute
  '/packages': typeof AuthenticatedAppPackagesRoute
  '/patients': typeof AuthenticatedAppPatientsRoute
  '/pharmacy': typeof AuthenticatedAppPharmacyRoute
  '/reports': typeof AuthenticatedAppReportsRoute
  '/settings': typeof AuthenticatedAppSettingsRoute
  '/staff': typeof AuthenticatedAppStaffRoute
  '/support-tickets': typeof AuthenticatedAppSupportTicketsRoute
  '/system-issues': typeof AuthenticatedAppSystemIssuesRoute
  '/tariffs': typeof AuthenticatedAppTariffsRoute
  '/unpaid': typeof AuthenticatedAppUnpaidRoute
  '/users': typeof AuthenticatedAppUsersRoute
  '/ward-setup': typeof AuthenticatedAppWardSetupRoute
  '/wards': typeof AuthenticatedAppWardsRoute
  '/tv/department/$departmentId': typeof TvDepartmentDepartmentIdRoute
  '/admissions/new': typeof AuthenticatedAppAdmissionsNewRoute
  '/consultations/$visitId': typeof AuthenticatedAppConsultationsVisitIdRoute
  '/doctors/$doctorId': typeof AuthenticatedAppDoctorsDoctorIdRoute
  '/ot/$bookingId': typeof AuthenticatedAppOtBookingIdRoute
  '/patients/$patientId': typeof AuthenticatedAppPatientsPatientIdRoute
  '/patients/new': typeof AuthenticatedAppPatientsNewRoute
  '/pharmacy/$prescriptionId': typeof AuthenticatedAppPharmacyPrescriptionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/forbidden': typeof ForbiddenRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/styleguide': typeof StyleguideRoute
  '/change-password': typeof AuthenticatedChangePasswordRoute
  '/tv/$doctorId': typeof TvDoctorIdRoute
  '/appointments': typeof AuthenticatedAppAppointmentsRoute
  '/approvals': typeof AuthenticatedAppApprovalsRoute
  '/audit-logs': typeof AuthenticatedAppAuditLogsRoute
  '/billing': typeof AuthenticatedAppBillingRoute
  '/cash-register': typeof AuthenticatedAppCashRegisterRoute
  '/company-settings': typeof AuthenticatedAppCompanySettingsRoute
  '/consultations': typeof AuthenticatedAppConsultationsRoute
  '/dashboard': typeof AuthenticatedAppDashboardRoute
  '/departments': typeof AuthenticatedAppDepartmentsRoute
  '/doctors': typeof AuthenticatedAppDoctorsRoute
  '/doctors-now': typeof AuthenticatedAppDoctorsNowRoute
  '/emergency': typeof AuthenticatedAppEmergencyRoute
  '/formulary': typeof AuthenticatedAppFormularyRoute
  '/handover': typeof AuthenticatedAppHandoverRoute
  '/help': typeof AuthenticatedAppHelpRoute
  '/inventory': typeof AuthenticatedAppInventoryRoute
  '/lab': typeof AuthenticatedAppLabRoute
  '/lab-tests': typeof AuthenticatedAppLabTestsRoute
  '/leave-approvals': typeof AuthenticatedAppLeaveApprovalsRoute
  '/my-appointments': typeof AuthenticatedAppMyAppointmentsRoute
  '/my-bills': typeof AuthenticatedAppMyBillsRoute
  '/my-day': typeof AuthenticatedAppMyDayRoute
  '/my-leave': typeof AuthenticatedAppMyLeaveRoute
  '/my-records': typeof AuthenticatedAppMyRecordsRoute
  '/my-schedule': typeof AuthenticatedAppMyScheduleRoute
  '/nursing': typeof AuthenticatedAppNursingRoute
  '/opd-queue': typeof AuthenticatedAppOpdQueueRoute
  '/ot': typeof AuthenticatedAppOtRoute
  '/packages': typeof AuthenticatedAppPackagesRoute
  '/patients': typeof AuthenticatedAppPatientsRoute
  '/pharmacy': typeof AuthenticatedAppPharmacyRoute
  '/reports': typeof AuthenticatedAppReportsRoute
  '/settings': typeof AuthenticatedAppSettingsRoute
  '/staff': typeof AuthenticatedAppStaffRoute
  '/support-tickets': typeof AuthenticatedAppSupportTicketsRoute
  '/system-issues': typeof AuthenticatedAppSystemIssuesRoute
  '/tariffs': typeof AuthenticatedAppTariffsRoute
  '/unpaid': typeof AuthenticatedAppUnpaidRoute
  '/users': typeof AuthenticatedAppUsersRoute
  '/ward-setup': typeof AuthenticatedAppWardSetupRoute
  '/wards': typeof AuthenticatedAppWardsRoute
  '/tv/department/$departmentId': typeof TvDepartmentDepartmentIdRoute
  '/admissions/new': typeof AuthenticatedAppAdmissionsNewRoute
  '/consultations/$visitId': typeof AuthenticatedAppConsultationsVisitIdRoute
  '/doctors/$doctorId': typeof AuthenticatedAppDoctorsDoctorIdRoute
  '/ot/$bookingId': typeof AuthenticatedAppOtBookingIdRoute
  '/patients/$patientId': typeof AuthenticatedAppPatientsPatientIdRoute
  '/patients/new': typeof AuthenticatedAppPatientsNewRoute
  '/pharmacy/$prescriptionId': typeof AuthenticatedAppPharmacyPrescriptionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/forbidden': typeof ForbiddenRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/styleguide': typeof StyleguideRoute
  '/_authenticated/_app': typeof AuthenticatedAppRouteRouteWithChildren
  '/_authenticated/change-password': typeof AuthenticatedChangePasswordRoute
  '/tv/$doctorId': typeof TvDoctorIdRoute
  '/_authenticated/_app/appointments': typeof AuthenticatedAppAppointmentsRoute
  '/_authenticated/_app/approvals': typeof AuthenticatedAppApprovalsRoute
  '/_authenticated/_app/audit-logs': typeof AuthenticatedAppAuditLogsRoute
  '/_authenticated/_app/billing': typeof AuthenticatedAppBillingRoute
  '/_authenticated/_app/cash-register': typeof AuthenticatedAppCashRegisterRoute
  '/_authenticated/_app/company-settings': typeof AuthenticatedAppCompanySettingsRoute
  '/_authenticated/_app/consultations': typeof AuthenticatedAppConsultationsRoute
  '/_authenticated/_app/dashboard': typeof AuthenticatedAppDashboardRoute
  '/_authenticated/_app/departments': typeof AuthenticatedAppDepartmentsRoute
  '/_authenticated/_app/doctors': typeof AuthenticatedAppDoctorsRoute
  '/_authenticated/_app/doctors-now': typeof AuthenticatedAppDoctorsNowRoute
  '/_authenticated/_app/emergency': typeof AuthenticatedAppEmergencyRoute
  '/_authenticated/_app/formulary': typeof AuthenticatedAppFormularyRoute
  '/_authenticated/_app/handover': typeof AuthenticatedAppHandoverRoute
  '/_authenticated/_app/help': typeof AuthenticatedAppHelpRoute
  '/_authenticated/_app/inventory': typeof AuthenticatedAppInventoryRoute
  '/_authenticated/_app/lab': typeof AuthenticatedAppLabRoute
  '/_authenticated/_app/lab-tests': typeof AuthenticatedAppLabTestsRoute
  '/_authenticated/_app/leave-approvals': typeof AuthenticatedAppLeaveApprovalsRoute
  '/_authenticated/_app/my-appointments': typeof AuthenticatedAppMyAppointmentsRoute
  '/_authenticated/_app/my-bills': typeof AuthenticatedAppMyBillsRoute
  '/_authenticated/_app/my-day': typeof AuthenticatedAppMyDayRoute
  '/_authenticated/_app/my-leave': typeof AuthenticatedAppMyLeaveRoute
  '/_authenticated/_app/my-records': typeof AuthenticatedAppMyRecordsRoute
  '/_authenticated/_app/my-schedule': typeof AuthenticatedAppMyScheduleRoute
  '/_authenticated/_app/nursing': typeof AuthenticatedAppNursingRoute
  '/_authenticated/_app/opd-queue': typeof AuthenticatedAppOpdQueueRoute
  '/_authenticated/_app/ot': typeof AuthenticatedAppOtRoute
  '/_authenticated/_app/packages': typeof AuthenticatedAppPackagesRoute
  '/_authenticated/_app/patients': typeof AuthenticatedAppPatientsRoute
  '/_authenticated/_app/pharmacy': typeof AuthenticatedAppPharmacyRoute
  '/_authenticated/_app/reports': typeof AuthenticatedAppReportsRoute
  '/_authenticated/_app/settings': typeof AuthenticatedAppSettingsRoute
  '/_authenticated/_app/staff': typeof AuthenticatedAppStaffRoute
  '/_authenticated/_app/support-tickets': typeof AuthenticatedAppSupportTicketsRoute
  '/_authenticated/_app/system-issues': typeof AuthenticatedAppSystemIssuesRoute
  '/_authenticated/_app/tariffs': typeof AuthenticatedAppTariffsRoute
  '/_authenticated/_app/unpaid': typeof AuthenticatedAppUnpaidRoute
  '/_authenticated/_app/users': typeof AuthenticatedAppUsersRoute
  '/_authenticated/_app/ward-setup': typeof AuthenticatedAppWardSetupRoute
  '/_authenticated/_app/wards': typeof AuthenticatedAppWardsRoute
  '/tv/department/$departmentId': typeof TvDepartmentDepartmentIdRoute
  '/_authenticated/_app/admissions_/new': typeof AuthenticatedAppAdmissionsNewRoute
  '/_authenticated/_app/consultations_/$visitId': typeof AuthenticatedAppConsultationsVisitIdRoute
  '/_authenticated/_app/doctors_/$doctorId': typeof AuthenticatedAppDoctorsDoctorIdRoute
  '/_authenticated/_app/ot_/$bookingId': typeof AuthenticatedAppOtBookingIdRoute
  '/_authenticated/_app/patients_/$patientId': typeof AuthenticatedAppPatientsPatientIdRoute
  '/_authenticated/_app/patients_/new': typeof AuthenticatedAppPatientsNewRoute
  '/_authenticated/_app/pharmacy_/$prescriptionId': typeof AuthenticatedAppPharmacyPrescriptionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/forbidden'
    | '/forgot-password'
    | '/reset-password'
    | '/styleguide'
    | '/change-password'
    | '/tv/$doctorId'
    | '/appointments'
    | '/approvals'
    | '/audit-logs'
    | '/billing'
    | '/cash-register'
    | '/company-settings'
    | '/consultations'
    | '/dashboard'
    | '/departments'
    | '/doctors'
    | '/doctors-now'
    | '/emergency'
    | '/formulary'
    | '/handover'
    | '/help'
    | '/inventory'
    | '/lab'
    | '/lab-tests'
    | '/leave-approvals'
    | '/my-appointments'
    | '/my-bills'
    | '/my-day'
    | '/my-leave'
    | '/my-records'
    | '/my-schedule'
    | '/nursing'
    | '/opd-queue'
    | '/ot'
    | '/packages'
    | '/patients'
    | '/pharmacy'
    | '/reports'
    | '/settings'
    | '/staff'
    | '/support-tickets'
    | '/system-issues'
    | '/tariffs'
    | '/unpaid'
    | '/users'
    | '/ward-setup'
    | '/wards'
    | '/tv/department/$departmentId'
    | '/admissions/new'
    | '/consultations/$visitId'
    | '/doctors/$doctorId'
    | '/ot/$bookingId'
    | '/patients/$patientId'
    | '/patients/new'
    | '/pharmacy/$prescriptionId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/forbidden'
    | '/forgot-password'
    | '/reset-password'
    | '/styleguide'
    | '/change-password'
    | '/tv/$doctorId'
    | '/appointments'
    | '/approvals'
    | '/audit-logs'
    | '/billing'
    | '/cash-register'
    | '/company-settings'
    | '/consultations'
    | '/dashboard'
    | '/departments'
    | '/doctors'
    | '/doctors-now'
    | '/emergency'
    | '/formulary'
    | '/handover'
    | '/help'
    | '/inventory'
    | '/lab'
    | '/lab-tests'
    | '/leave-approvals'
    | '/my-appointments'
    | '/my-bills'
    | '/my-day'
    | '/my-leave'
    | '/my-records'
    | '/my-schedule'
    | '/nursing'
    | '/opd-queue'
    | '/ot'
    | '/packages'
    | '/patients'
    | '/pharmacy'
    | '/reports'
    | '/settings'
    | '/staff'
    | '/support-tickets'
    | '/system-issues'
    | '/tariffs'
    | '/unpaid'
    | '/users'
    | '/ward-setup'
    | '/wards'
    | '/tv/department/$departmentId'
    | '/admissions/new'
    | '/consultations/$visitId'
    | '/doctors/$doctorId'
    | '/ot/$bookingId'
    | '/patients/$patientId'
    | '/patients/new'
    | '/pharmacy/$prescriptionId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/forbidden'
    | '/forgot-password'
    | '/reset-password'
    | '/styleguide'
    | '/_authenticated/_app'
    | '/_authenticated/change-password'
    | '/tv/$doctorId'
    | '/_authenticated/_app/appointments'
    | '/_authenticated/_app/approvals'
    | '/_authenticated/_app/audit-logs'
    | '/_authenticated/_app/billing'
    | '/_authenticated/_app/cash-register'
    | '/_authenticated/_app/company-settings'
    | '/_authenticated/_app/consultations'
    | '/_authenticated/_app/dashboard'
    | '/_authenticated/_app/departments'
    | '/_authenticated/_app/doctors'
    | '/_authenticated/_app/doctors-now'
    | '/_authenticated/_app/emergency'
    | '/_authenticated/_app/formulary'
    | '/_authenticated/_app/handover'
    | '/_authenticated/_app/help'
    | '/_authenticated/_app/inventory'
    | '/_authenticated/_app/lab'
    | '/_authenticated/_app/lab-tests'
    | '/_authenticated/_app/leave-approvals'
    | '/_authenticated/_app/my-appointments'
    | '/_authenticated/_app/my-bills'
    | '/_authenticated/_app/my-day'
    | '/_authenticated/_app/my-leave'
    | '/_authenticated/_app/my-records'
    | '/_authenticated/_app/my-schedule'
    | '/_authenticated/_app/nursing'
    | '/_authenticated/_app/opd-queue'
    | '/_authenticated/_app/ot'
    | '/_authenticated/_app/packages'
    | '/_authenticated/_app/patients'
    | '/_authenticated/_app/pharmacy'
    | '/_authenticated/_app/reports'
    | '/_authenticated/_app/settings'
    | '/_authenticated/_app/staff'
    | '/_authenticated/_app/support-tickets'
    | '/_authenticated/_app/system-issues'
    | '/_authenticated/_app/tariffs'
    | '/_authenticated/_app/unpaid'
    | '/_authenticated/_app/users'
    | '/_authenticated/_app/ward-setup'
    | '/_authenticated/_app/wards'
    | '/tv/department/$departmentId'
    | '/_authenticated/_app/admissions_/new'
    | '/_authenticated/_app/consultations_/$visitId'
    | '/_authenticated/_app/doctors_/$doctorId'
    | '/_authenticated/_app/ot_/$bookingId'
    | '/_authenticated/_app/patients_/$patientId'
    | '/_authenticated/_app/patients_/new'
    | '/_authenticated/_app/pharmacy_/$prescriptionId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ForbiddenRoute: typeof ForbiddenRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  StyleguideRoute: typeof StyleguideRoute
  TvDoctorIdRoute: typeof TvDoctorIdRoute
  TvDepartmentDepartmentIdRoute: typeof TvDepartmentDepartmentIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forbidden': {
      id: '/forbidden'
      path: '/forbidden'
      fullPath: '/forbidden'
      preLoaderRoute: typeof ForbiddenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/styleguide': {
      id: '/styleguide'
      path: '/styleguide'
      fullPath: '/styleguide'
      preLoaderRoute: typeof StyleguideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/_app': {
      id: '/_authenticated/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedAppRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/change-password': {
      id: '/_authenticated/change-password'
      path: '/change-password'
      fullPath: '/change-password'
      preLoaderRoute: typeof AuthenticatedChangePasswordRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/tv/$doctorId': {
      id: '/tv/$doctorId'
      path: '/tv/$doctorId'
      fullPath: '/tv/$doctorId'
      preLoaderRoute: typeof TvDoctorIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/_app/appointments': {
      id: '/_authenticated/_app/appointments'
      path: '/appointments'
      fullPath: '/appointments'
      preLoaderRoute: typeof AuthenticatedAppAppointmentsRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/_app/approvals': {
      id: '/_authenticated/_app/approvals'
      path: '/approvals'
      fullPath: '/approvals'
      preLoaderRoute: typeof AuthenticatedAppApprovalsRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/_app/audit-logs': {
      id: '/_authenticated/_app/audit-logs'
      path: '/audit-logs'
      fullPath: '/audit-logs'
      preLoaderRoute: typeof AuthenticatedAppAuditLogsRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/_app/billing': {
      id: '/_authenticated/_app/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof AuthenticatedAppBillingRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/_app/cash-register': {
      id: '/_authenticated/_app/cash-register'
      path: '/cash-register'
      fullPath: '/cash-register'
      preLoaderRoute: typeof AuthenticatedAppCashRegisterRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/_app/company-settings': {
      id: '/_authenticated/_app/company-settings'
      path: '/company-settings'
      fullPath: '/company-settings'
      preLoaderRoute: typeof AuthenticatedAppCompanySettingsRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/_app/consultations': {
      id: '/_authenticated/_app/consultations'
      path: '/consultations'
      fullPath: '/consultations'
      preLoaderRoute: typeof AuthenticatedAppConsultationsRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/_app/dashboard': {
      id: '/_authenticated/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedAppDashboardRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/_app/departments': {
      id: '/_authenticated/_app/departments'
      path: '/departments'
      fullPath: '/departments'
      preLoaderRoute: typeof AuthenticatedAppDepartmentsRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/_app/doctors': {
      id: '/_authenticated/_app/doctors'
      path: '/doctors'
      fullPath: '/doctors'
      preLoaderRoute: typeof AuthenticatedAppDoctorsRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/_app/doctors-now': {
      id: '/_authenticated/_app/doctors-now'
      path: '/doctors-now'
      fullPath: '/doctors-now'
      preLoaderRoute: typeof AuthenticatedAppDoctorsNowRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/_app/emergency': {
      id: '/_authenticated/_app/emergency'
      path: '/emergency'
      fullPath: '/emergency'
      preLoaderRoute: typeof AuthenticatedAppEmergencyRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/_app/formulary': {
      id: '/_authenticated/_app/formulary'
      path: '/formulary'
      fullPath: '/formulary'
      preLoaderRoute: typeof AuthenticatedAppFormularyRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/_app/handover': {
      id: '/_authenticated/_app/handover'
      path: '/handover'
      fullPath: '/handover'
      preLoaderRoute: typeof AuthenticatedAppHandoverRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/_app/help': {
      id: '/_authenticated/_app/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof AuthenticatedAppHelpRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/_app/inventory': {
      id: '/_authenticated/_app/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof AuthenticatedAppInventoryRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/_app/lab': {
      id: '/_authenticated/_app/lab'
      path: '/lab'
      fullPath: '/lab'
      preLoaderRoute: typeof AuthenticatedAppLabRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/_app/lab-tests': {
      id: '/_authenticated/_app/lab-tests'
      path: '/lab-tests'
      fullPath: '/lab-tests'
      preLoaderRoute: typeof AuthenticatedAppLabTestsRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/_app/leave-approvals': {
      id: '/_authenticated/_app/leave-approvals'
      path: '/leave-approvals'
      fullPath: '/leave-approvals'
      preLoaderRoute: typeof AuthenticatedAppLeaveApprovalsRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/_app/my-appointments': {
      id: '/_authenticated/_app/my-appointments'
      path: '/my-appointments'
      fullPath: '/my-appointments'
      preLoaderRoute: typeof AuthenticatedAppMyAppointmentsRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/_app/my-bills': {
      id: '/_authenticated/_app/my-bills'
      path: '/my-bills'
      fullPath: '/my-bills'
      preLoaderRoute: typeof AuthenticatedAppMyBillsRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/_app/my-day': {
      id: '/_authenticated/_app/my-day'
      path: '/my-day'
      fullPath: '/my-day'
      preLoaderRoute: typeof AuthenticatedAppMyDayRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/_app/my-leave': {
      id: '/_authenticated/_app/my-leave'
      path: '/my-leave'
      fullPath: '/my-leave'
      preLoaderRoute: typeof AuthenticatedAppMyLeaveRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/_app/my-records': {
      id: '/_authenticated/_app/my-records'
      path: '/my-records'
      fullPath: '/my-records'
      preLoaderRoute: typeof AuthenticatedAppMyRecordsRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/_app/my-schedule': {
      id: '/_authenticated/_app/my-schedule'
      path: '/my-schedule'
      fullPath: '/my-schedule'
      preLoaderRoute: typeof AuthenticatedAppMyScheduleRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/_app/nursing': {
      id: '/_authenticated/_app/nursing'
      path: '/nursing'
      fullPath: '/nursing'
      preLoaderRoute: typeof AuthenticatedAppNursingRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/_app/opd-queue': {
      id: '/_authenticated/_app/opd-queue'
      path: '/opd-queue'
      fullPath: '/opd-queue'
      preLoaderRoute: typeof AuthenticatedAppOpdQueueRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/_app/ot': {
      id: '/_authenticated/_app/ot'
      path: '/ot'
      fullPath: '/ot'
      preLoaderRoute: typeof AuthenticatedAppOtRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/_app/packages': {
      id: '/_authenticated/_app/packages'
      path: '/packages'
      fullPath: '/packages'
      preLoaderRoute: typeof AuthenticatedAppPackagesRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/_app/patients': {
      id: '/_authenticated/_app/patients'
      path: '/patients'
      fullPath: '/patients'
      preLoaderRoute: typeof AuthenticatedAppPatientsRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/_app/pharmacy': {
      id: '/_authenticated/_app/pharmacy'
      path: '/pharmacy'
      fullPath: '/pharmacy'
      preLoaderRoute: typeof AuthenticatedAppPharmacyRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/_app/reports': {
      id: '/_authenticated/_app/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedAppReportsRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/_app/settings': {
      id: '/_authenticated/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedAppSettingsRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/_app/staff': {
      id: '/_authenticated/_app/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof AuthenticatedAppStaffRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/_app/support-tickets': {
      id: '/_authenticated/_app/support-tickets'
      path: '/support-tickets'
      fullPath: '/support-tickets'
      preLoaderRoute: typeof AuthenticatedAppSupportTicketsRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/_app/system-issues': {
      id: '/_authenticated/_app/system-issues'
      path: '/system-issues'
      fullPath: '/system-issues'
      preLoaderRoute: typeof AuthenticatedAppSystemIssuesRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/_app/tariffs': {
      id: '/_authenticated/_app/tariffs'
      path: '/tariffs'
      fullPath: '/tariffs'
      preLoaderRoute: typeof AuthenticatedAppTariffsRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/_app/unpaid': {
      id: '/_authenticated/_app/unpaid'
      path: '/unpaid'
      fullPath: '/unpaid'
      preLoaderRoute: typeof AuthenticatedAppUnpaidRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/_app/users': {
      id: '/_authenticated/_app/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedAppUsersRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/_app/ward-setup': {
      id: '/_authenticated/_app/ward-setup'
      path: '/ward-setup'
      fullPath: '/ward-setup'
      preLoaderRoute: typeof AuthenticatedAppWardSetupRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/_app/wards': {
      id: '/_authenticated/_app/wards'
      path: '/wards'
      fullPath: '/wards'
      preLoaderRoute: typeof AuthenticatedAppWardsRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/tv/department/$departmentId': {
      id: '/tv/department/$departmentId'
      path: '/tv/department/$departmentId'
      fullPath: '/tv/department/$departmentId'
      preLoaderRoute: typeof TvDepartmentDepartmentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/_app/admissions_/new': {
      id: '/_authenticated/_app/admissions_/new'
      path: '/admissions/new'
      fullPath: '/admissions/new'
      preLoaderRoute: typeof AuthenticatedAppAdmissionsNewRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/_app/consultations_/$visitId': {
      id: '/_authenticated/_app/consultations_/$visitId'
      path: '/consultations/$visitId'
      fullPath: '/consultations/$visitId'
      preLoaderRoute: typeof AuthenticatedAppConsultationsVisitIdRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/_app/doctors_/$doctorId': {
      id: '/_authenticated/_app/doctors_/$doctorId'
      path: '/doctors/$doctorId'
      fullPath: '/doctors/$doctorId'
      preLoaderRoute: typeof AuthenticatedAppDoctorsDoctorIdRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/_app/ot_/$bookingId': {
      id: '/_authenticated/_app/ot_/$bookingId'
      path: '/ot/$bookingId'
      fullPath: '/ot/$bookingId'
      preLoaderRoute: typeof AuthenticatedAppOtBookingIdRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/_app/patients_/$patientId': {
      id: '/_authenticated/_app/patients_/$patientId'
      path: '/patients/$patientId'
      fullPath: '/patients/$patientId'
      preLoaderRoute: typeof AuthenticatedAppPatientsPatientIdRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/_app/patients_/new': {
      id: '/_authenticated/_app/patients_/new'
      path: '/patients/new'
      fullPath: '/patients/new'
      preLoaderRoute: typeof AuthenticatedAppPatientsNewRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/_app/pharmacy_/$prescriptionId': {
      id: '/_authenticated/_app/pharmacy_/$prescriptionId'
      path: '/pharmacy/$prescriptionId'
      fullPath: '/pharmacy/$prescriptionId'
      preLoaderRoute: typeof AuthenticatedAppPharmacyPrescriptionIdRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
  }
}

interface AuthenticatedAppRouteRouteChildren {
  AuthenticatedAppAppointmentsRoute: typeof AuthenticatedAppAppointmentsRoute
  AuthenticatedAppApprovalsRoute: typeof AuthenticatedAppApprovalsRoute
  AuthenticatedAppAuditLogsRoute: typeof AuthenticatedAppAuditLogsRoute
  AuthenticatedAppBillingRoute: typeof AuthenticatedAppBillingRoute
  AuthenticatedAppCashRegisterRoute: typeof AuthenticatedAppCashRegisterRoute
  AuthenticatedAppCompanySettingsRoute: typeof AuthenticatedAppCompanySettingsRoute
  AuthenticatedAppConsultationsRoute: typeof AuthenticatedAppConsultationsRoute
  AuthenticatedAppDashboardRoute: typeof AuthenticatedAppDashboardRoute
  AuthenticatedAppDepartmentsRoute: typeof AuthenticatedAppDepartmentsRoute
  AuthenticatedAppDoctorsRoute: typeof AuthenticatedAppDoctorsRoute
  AuthenticatedAppDoctorsNowRoute: typeof AuthenticatedAppDoctorsNowRoute
  AuthenticatedAppEmergencyRoute: typeof AuthenticatedAppEmergencyRoute
  AuthenticatedAppFormularyRoute: typeof AuthenticatedAppFormularyRoute
  AuthenticatedAppHandoverRoute: typeof AuthenticatedAppHandoverRoute
  AuthenticatedAppHelpRoute: typeof AuthenticatedAppHelpRoute
  AuthenticatedAppInventoryRoute: typeof AuthenticatedAppInventoryRoute
  AuthenticatedAppLabRoute: typeof AuthenticatedAppLabRoute
  AuthenticatedAppLabTestsRoute: typeof AuthenticatedAppLabTestsRoute
  AuthenticatedAppLeaveApprovalsRoute: typeof AuthenticatedAppLeaveApprovalsRoute
  AuthenticatedAppMyAppointmentsRoute: typeof AuthenticatedAppMyAppointmentsRoute
  AuthenticatedAppMyBillsRoute: typeof AuthenticatedAppMyBillsRoute
  AuthenticatedAppMyDayRoute: typeof AuthenticatedAppMyDayRoute
  AuthenticatedAppMyLeaveRoute: typeof AuthenticatedAppMyLeaveRoute
  AuthenticatedAppMyRecordsRoute: typeof AuthenticatedAppMyRecordsRoute
  AuthenticatedAppMyScheduleRoute: typeof AuthenticatedAppMyScheduleRoute
  AuthenticatedAppNursingRoute: typeof AuthenticatedAppNursingRoute
  AuthenticatedAppOpdQueueRoute: typeof AuthenticatedAppOpdQueueRoute
  AuthenticatedAppOtRoute: typeof AuthenticatedAppOtRoute
  AuthenticatedAppPackagesRoute: typeof AuthenticatedAppPackagesRoute
  AuthenticatedAppPatientsRoute: typeof AuthenticatedAppPatientsRoute
  AuthenticatedAppPharmacyRoute: typeof AuthenticatedAppPharmacyRoute
  AuthenticatedAppReportsRoute: typeof AuthenticatedAppReportsRoute
  AuthenticatedAppSettingsRoute: typeof AuthenticatedAppSettingsRoute
  AuthenticatedAppStaffRoute: typeof AuthenticatedAppStaffRoute
  AuthenticatedAppSupportTicketsRoute: typeof AuthenticatedAppSupportTicketsRoute
  AuthenticatedAppSystemIssuesRoute: typeof AuthenticatedAppSystemIssuesRoute
  AuthenticatedAppTariffsRoute: typeof AuthenticatedAppTariffsRoute
  AuthenticatedAppUnpaidRoute: typeof AuthenticatedAppUnpaidRoute
  AuthenticatedAppUsersRoute: typeof AuthenticatedAppUsersRoute
  AuthenticatedAppWardSetupRoute: typeof AuthenticatedAppWardSetupRoute
  AuthenticatedAppWardsRoute: typeof AuthenticatedAppWardsRoute
  AuthenticatedAppAdmissionsNewRoute: typeof AuthenticatedAppAdmissionsNewRoute
  AuthenticatedAppConsultationsVisitIdRoute: typeof AuthenticatedAppConsultationsVisitIdRoute
  AuthenticatedAppDoctorsDoctorIdRoute: typeof AuthenticatedAppDoctorsDoctorIdRoute
  AuthenticatedAppOtBookingIdRoute: typeof AuthenticatedAppOtBookingIdRoute
  AuthenticatedAppPatientsPatientIdRoute: typeof AuthenticatedAppPatientsPatientIdRoute
  AuthenticatedAppPatientsNewRoute: typeof AuthenticatedAppPatientsNewRoute
  AuthenticatedAppPharmacyPrescriptionIdRoute: typeof AuthenticatedAppPharmacyPrescriptionIdRoute
}

const AuthenticatedAppRouteRouteChildren: AuthenticatedAppRouteRouteChildren = {
  AuthenticatedAppAppointmentsRoute: AuthenticatedAppAppointmentsRoute,
  AuthenticatedAppApprovalsRoute: AuthenticatedAppApprovalsRoute,
  AuthenticatedAppAuditLogsRoute: AuthenticatedAppAuditLogsRoute,
  AuthenticatedAppBillingRoute: AuthenticatedAppBillingRoute,
  AuthenticatedAppCashRegisterRoute: AuthenticatedAppCashRegisterRoute,
  AuthenticatedAppCompanySettingsRoute: AuthenticatedAppCompanySettingsRoute,
  AuthenticatedAppConsultationsRoute: AuthenticatedAppConsultationsRoute,
  AuthenticatedAppDashboardRoute: AuthenticatedAppDashboardRoute,
  AuthenticatedAppDepartmentsRoute: AuthenticatedAppDepartmentsRoute,
  AuthenticatedAppDoctorsRoute: AuthenticatedAppDoctorsRoute,
  AuthenticatedAppDoctorsNowRoute: AuthenticatedAppDoctorsNowRoute,
  AuthenticatedAppEmergencyRoute: AuthenticatedAppEmergencyRoute,
  AuthenticatedAppFormularyRoute: AuthenticatedAppFormularyRoute,
  AuthenticatedAppHandoverRoute: AuthenticatedAppHandoverRoute,
  AuthenticatedAppHelpRoute: AuthenticatedAppHelpRoute,
  AuthenticatedAppInventoryRoute: AuthenticatedAppInventoryRoute,
  AuthenticatedAppLabRoute: AuthenticatedAppLabRoute,
  AuthenticatedAppLabTestsRoute: AuthenticatedAppLabTestsRoute,
  AuthenticatedAppLeaveApprovalsRoute: AuthenticatedAppLeaveApprovalsRoute,
  AuthenticatedAppMyAppointmentsRoute: AuthenticatedAppMyAppointmentsRoute,
  AuthenticatedAppMyBillsRoute: AuthenticatedAppMyBillsRoute,
  AuthenticatedAppMyDayRoute: AuthenticatedAppMyDayRoute,
  AuthenticatedAppMyLeaveRoute: AuthenticatedAppMyLeaveRoute,
  AuthenticatedAppMyRecordsRoute: AuthenticatedAppMyRecordsRoute,
  AuthenticatedAppMyScheduleRoute: AuthenticatedAppMyScheduleRoute,
  AuthenticatedAppNursingRoute: AuthenticatedAppNursingRoute,
  AuthenticatedAppOpdQueueRoute: AuthenticatedAppOpdQueueRoute,
  AuthenticatedAppOtRoute: AuthenticatedAppOtRoute,
  AuthenticatedAppPackagesRoute: AuthenticatedAppPackagesRoute,
  AuthenticatedAppPatientsRoute: AuthenticatedAppPatientsRoute,
  AuthenticatedAppPharmacyRoute: AuthenticatedAppPharmacyRoute,
  AuthenticatedAppReportsRoute: AuthenticatedAppReportsRoute,
  AuthenticatedAppSettingsRoute: AuthenticatedAppSettingsRoute,
  AuthenticatedAppStaffRoute: AuthenticatedAppStaffRoute,
  AuthenticatedAppSupportTicketsRoute: AuthenticatedAppSupportTicketsRoute,
  AuthenticatedAppSystemIssuesRoute: AuthenticatedAppSystemIssuesRoute,
  AuthenticatedAppTariffsRoute: AuthenticatedAppTariffsRoute,
  AuthenticatedAppUnpaidRoute: AuthenticatedAppUnpaidRoute,
  AuthenticatedAppUsersRoute: AuthenticatedAppUsersRoute,
  AuthenticatedAppWardSetupRoute: AuthenticatedAppWardSetupRoute,
  AuthenticatedAppWardsRoute: AuthenticatedAppWardsRoute,
  AuthenticatedAppAdmissionsNewRoute: AuthenticatedAppAdmissionsNewRoute,
  AuthenticatedAppConsultationsVisitIdRoute:
    AuthenticatedAppConsultationsVisitIdRoute,
  AuthenticatedAppDoctorsDoctorIdRoute: AuthenticatedAppDoctorsDoctorIdRoute,
  AuthenticatedAppOtBookingIdRoute: AuthenticatedAppOtBookingIdRoute,
  AuthenticatedAppPatientsPatientIdRoute:
    AuthenticatedAppPatientsPatientIdRoute,
  AuthenticatedAppPatientsNewRoute: AuthenticatedAppPatientsNewRoute,
  AuthenticatedAppPharmacyPrescriptionIdRoute:
    AuthenticatedAppPharmacyPrescriptionIdRoute,
}

const AuthenticatedAppRouteRouteWithChildren =
  AuthenticatedAppRouteRoute._addFileChildren(
    AuthenticatedAppRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAppRouteRoute: typeof AuthenticatedAppRouteRouteWithChildren
  AuthenticatedChangePasswordRoute: typeof AuthenticatedChangePasswordRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAppRouteRoute: AuthenticatedAppRouteRouteWithChildren,
  AuthenticatedChangePasswordRoute: AuthenticatedChangePasswordRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ForbiddenRoute: ForbiddenRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  StyleguideRoute: StyleguideRoute,
  TvDoctorIdRoute: TvDoctorIdRoute,
  TvDepartmentDepartmentIdRoute: TvDepartmentDepartmentIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
