// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vsfdfxlpxdxwxwaqwjku.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZzZmRmeGxweGR4d3h3YXF3amt1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODk4MjkyOTQsImV4cCI6MjEwNTQwNTI5NH0.i4YJNg58OdfuPLaCdDUU3QRRkK5T5apuBkYouHTKwTQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: typeof window !== 'undefined' ? localStorage : undefined,
    persistSession: true,
    autoRefreshToken: true,
  }
});